module.exports={
    sql_config:{
        host:'101.201.235.23',
        user:'root',
        password:'daiming',
        port:3306,
        database:'daiming'
    },
    dev_db:{
        host:'127.0.0.1',
        user:'root',
        password:'daiming',
        port:3306,
        database:'blog_sql'
    }
}